//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InvNew.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_X                  101
#define ID_INDICATOR_Z                  102
#define ID_INDICATOR_COMPUTE            103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_INDICATOR_PROFILE            105
#define ID_INDICATOR_METHOD             106
#define IDR_MAINFRAME                   128
#define IDR_InversionTYPE               129
#define IDD_DLG_DTB_IMPORT              130
#define ID_DATABASE_IMPORT              131
#define ID_METHOD_WERNER                132
#define IDB_B1                          133
#define IDB_B2                          135
#define ID_VIEW_ZOOM_PAGE               136
#define ID_VIEW_ZOOM                    137
#define ID_VIEW_ZOOM_IN                 138
#define ID_VIEW_ZOOM_OUT                139
#define IDC_CURSOR_HSCROLL              140
#define IDC_CURSOR_VSCROLL              142
#define IDD_DLG_WERNER                  143
#define IDD_DLG_SETRANGE                144
#define IDD_DLG_CLUSTERING              145
#define ID_METHOD_CLUSTERING            146
#define ID_Menu                         147
#define ID_VIEW_REDRAW                  148
#define IDD_DLG_CLUSTRING_SMALL         149
#define IDD_DLG_SELCHAN                 150
#define ID_VIEW_SETCHANNELS             151
#define ID_EDIT_METHOD                  152
#define ID_EDIT_REMOVEHIDEN             153
#define IDD_DLG_METHOD_EDIT             154
#define ID_EDIT_DELETE_METHOD           155
#define ID_METHOD_EXPORT                156
#define ID_DATABASE_COMPUTE             157
#define ID_DATABASE_PROFILE_NEXT        158
#define ID_DATABASE_PROFILE_PREV        159
#define ID_DATABASE_PROFILE_FIRST       160
#define ID_DATABASE_PROFILE_LAST        161
#define IDD_DLG_METHOD_PROPERTIES       162
#define IDB_BKG                         163
#define IDD_REGULARIZATION_DIALOG       164
#define IDC_CURSOR_REGPAR               165
#define IDD_DLG_SETPROFCHAN             166
#define IDD_DLG_FILTER_RESULTS          169
#define ID_METHOD_FILTER_RESULTS        170
#define IDC_SOL_NAME                    1000
#define IDC_BUT_INPORT                  1000
#define IDC_EDIT_MIN                    1002
#define IDC_BUT_REGULARIZE              1002
#define IDC_EDIT_MAX                    1003
#define IDC_EDIT_RP_MIN                 1003
#define IDC_RADIO_CLUST                 1004
#define IDC_EDIT_RP_MAX                 1004
#define IDC_RADIO2                      1005
#define IDC_EDIT_TRESH                  1006
#define IDC_EDIT_RP_Q                   1006
#define IDC_BUTTON_APPLY                1006
#define IDC_SPIN_TRESH                  1007
#define IDC_RADIO_REGTAG                1007
#define IDC_EDIT_RADIUS                 1008
#define IDC_BUTTON_COMPUTE              1009
#define IDC_RADIO3                      1009
#define IDC_STR_SOLNAME                 1010
#define IDC_EDIT_EXP                    1010
#define IDC_EDIT_FLD_CONT               1010
#define IDC_STR_PROFILE                 1011
#define IDC_SPIN_EXP                    1011
#define IDC_BUT_DEFAULT                 1011
#define IDC_STR_WW                      1012
#define IDC_WWSTART                     1013
#define IDC_STR_IP                      1013
#define IDC_WWEND                       1014
#define IDC_CHAN_POS                    1014
#define IDC_CHAN_ELEV                   1015
#define IDC_CHECK_DATA                  1015
#define IDC_IPSTART                     1016
#define IDC_CHAN_FLD                    1016
#define IDC_CHECK_RGLRZ                 1016
#define IDC_EDIT_CHISQ                  1016
#define IDC_IPEND                       1017
#define IDC_LIST_METH                   1017
#define IDC_CHECK_FFT                   1017
#define IDC_STATIC_SI                   1017
#define IDC_FIELDSTREN                  1018
#define IDC_BUT_DEL                     1018
#define IDC_CHECK_SPEC                  1018
#define IDC_STATIC_SI_START             1018
#define IDC_INLC                        1019
#define IDC_BUT_PROP                    1019
#define IDC_STATIC_SI_END               1019
#define IDC_DECL                        1020
#define IDC_BUT_REMHID                  1020
#define IDC_RADIO_ALL                   1020
#define IDC_MIN_ELEV                    1021
#define IDC_RADIO_SHOW_PROF             1021
#define IDC_MAX_ELEV                    1022
#define IDC_WWSTEP                      1023
#define IDC_BUT_SHOW                    1023
#define IDC_BUT_PREV_MIN                1023
#define IDC_BUT_METHCUR                 1024
#define IDC_BUT_NEXT_MIN                1024
#define IDC_BUT_EXPORT                  1025
#define IDC_BUT_COLOR                   1026
#define IDC_EDIT_ID                     1027
#define IDC_EDIT_PROF                   1030
#define IDC_EDIT_TYPE                   1031
#define IDC_EDIT_NUMSOL                 1032
#define IDC_EDIT_IP                     1033
#define IDC_EDIT_WW                     1034
#define IDC_CLOSE                       1038
#define IDC_CANCEL                      1039
#define IDC_EDIT_IP_START               1039
#define IDC_BUT_HLP                     1040
#define IDC_EDIT_WW_START               1040
#define IDC_BUT_SETDATA                 1041
#define IDC_EDIT_WW_END                 1041
#define IDC_COMBO_PROF                  1042
#define IDC_EDIT_WW_STARTPOS            1042
#define IDC_COMBO_CHAN                  1043
#define IDC_RADIO1                      1043
#define IDC_EDIT_WW_ENDPOS              1043
#define IDC_RADIO_OUT                   1044
#define IDC_EDIT_SI_START               1044
#define IDC_EDIT_IP_END                 1048
#define IDC_EDIT_CONDNUM                1049
#define IDC_EDIT_SI_END                 1050
#define IDC_EDIT_ALTITUDE_MAX           1051
#define IDC_EDIT_ALTITUDE_MIN           1052
#define IDC_SHOW_ALL                    1056
#define IDC_CHANNEL_FIELD               1226
#define IDC_CHANNEL_POS                 1227
#define IDC_CHANNEL_ALTITUDE            1228
#define IDC_WD_PROF                     1257
#define IDC_EDIT_NAME                   1280
#define IDC_LIST_CHAN                   1293
#define IDC_BUTTON_DEFAULT              1305

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
